### ISSUE TITLE
cleaner가 너무 깨끗하게 정리해줘요..

### ISSUE THREAD

**Issue by long8v** [tndls9304/nlp_torch_study#16]
![image](https://user-images.githubusercontent.com/46675408/117288536-9145b180-aea6-11eb-8f78-76d31344bff3.png)
run 예시대로 했는데 뭔가 잘못한걸까요?

**Comment by tndls9304** [comment]
min space 가 5 기 때문에 space 가 1개 있는 문장은 다 지워 버립니다.
너무 짧은 문장을 거르려고 넣은 설정입니다.
config 조절해서 사용해주세요.
올리기 전에 comment 읽어 주셨으면 좋겠네요.

**Comment by long8v** [comment]
아 그렇군요 감사합니다!!
